import {initial,accrue,cast,collect,claimDaily,species,zones,baitPrice,rollFish} from './engine.js';
const $=id=>document.getElementById(id);const key='laguna-pixel-v1';let state=initial(),tab='fish';try{const s=JSON.parse(localStorage.getItem(key));if(s?.version===1&&['fin','cash','pending','last'].every(k=>Number.isFinite(s[k])&&s[k]>=0)&&Array.isArray(s.fish)&&s.fish.every(i=>Number.isInteger(i)&&species[i]))state=s;}catch{}
state.baits=Array.isArray(state.baits)&&state.baits.length===4?state.baits.map(n=>Number.isInteger(n)&&n>=0?n:0):[Number.isInteger(state.bait)&&state.bait>=0?state.bait:0,0,0,0];let zone=0;
function zonePicker(){return '<div class="cards">'+zones.map((z,i)=>'<button data-zone="'+i+'" aria-pressed="'+(zone===i)+'">'+z.name+'</button>').join('')+'</div><p>'+[0,3,1,2,4].map(i=>species[i].rarity+' '+zones[zone].weights[i]+'%').join(' · ')+'</p>';}
function bindZones(){document.querySelectorAll('[data-zone]').forEach(b=>{if(+b.dataset.zone===zone)b.style.outline='3px solid #b49b57';b.onclick=()=>{zone=+b.dataset.zone;render();};});}
const fmt=n=>n.toLocaleString('es',{maximumFractionDigits:2});function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('status').textContent='El navegador no permite guardar. Tu progreso durará esta sesión.';}}function update(){state=accrue(state);$('fin').textContent=fmt(state.fin);$('cash').textContent=fmt(state.cash);$('pending').textContent=fmt(state.pending);$('production').textContent=fmt(state.fish.reduce((n,i)=>n+species[i].rate,0))+' CASH / día';$('collection').disabled=state.pending<=0;}
function render(){update();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const panel=$('panel');if(tab==='fish'){panel.innerHTML='<h2>Elige dónde pescar</h2>'+zonePicker()+'<p>'+state.baits[zone]+' cebos de '+zones[zone].name+' disponibles.</p><button id="go">Ir a '+zones[zone].name+'</button>';$('go').onclick=openRiver;bindZones();}else if(tab==='shop'){panel.innerHTML='<h2>Tienda de cebos</h2>'+zonePicker()+'<p>Cebos exclusivos de '+zones[zone].name+'. Cada intento consume uno.</p><div class="cards">'+[1,5,11].map(n=>`<button data-buy="${n}">${n} cebos<small>${fmt(baitPrice(zone,n))} FIN</small></button>`).join('')+'</div>';bindZones();panel.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>action(()=>{const n=+b.dataset.buy,cost=baitPrice(zone,n);if(state.fin<cost)throw Error('FIN insuficientes');state.fin-=cost;state.baits[zone]+=n;return 'Compraste '+n+' cebos de '+zones[zone].name+'.';}));}else if(tab==='inventory'){panel.innerHTML='<h2>Tu colección</h2>'+species.map((f,i)=>{const n=state.fish.filter(j=>j===i).length;return `<div class="row"><span>${f.name} ×${n}<small>${f.rarity} · ${f.rate} CASH por pez/día</small></span><strong>${n*f.rate} / día</strong></div>`}).join('');}else if(tab==='tasks'){panel.innerHTML='<h2>Tarea diaria</h2><p>Vuelve cada día para recibir 1,300 FIN de prueba. El día se renueva a las 00:00 UTC.</p><button id="daily">Recoger recompensa</button>';$('daily').disabled=state.daily===new Date().toISOString().slice(0,10);$('daily').onclick=()=>action(()=>{state=claimDaily(state);return 'Recibiste 1,300 FIN.';});}else{panel.innerHTML='<h2>Billetera de prueba</h2><p>Saldo: <strong>'+fmt(state.cash)+' CASH</strong></p><p class="notice">Esta demo no acepta depósitos ni procesa retiros. Los saldos se guardan en este dispositivo y no tienen valor monetario.</p><button id="demo-topup">Añadir 10,000 FIN de prueba</button>';$('demo-topup').onclick=()=>action(()=>{state.fin+=10000;return 'Añadidos 10,000 FIN de prueba. Puedes volver a comprar cebos.';});}}
function action(fn){try{const message=fn();save();render();$('status').textContent=message;}catch(e){$('status').textContent=e.message;}}
$('collection').onclick=()=>action(()=>{state=collect(state);return 'CASH acumulado recogido.';});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});render();setInterval(()=>{update();save();},1000);
const canvas=$('water'),ctx=canvas.getContext('2d');canvas.width=480;canvas.height=440;ctx.scale(2,2);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function draw(time){const t=reduced?0:time/1000;const g=ctx.createLinearGradient(0,0,0,220);g.addColorStop(0,'#43c4cf');g.addColorStop(.35,'#118cb5');g.addColorStop(1,'#073f6d');ctx.fillStyle=g;ctx.fillRect(0,0,240,220);
// Shifting surface ripples and sunlight shafts.
for(let i=0;i<8;i++){ctx.fillStyle='rgba(163,247,232,.055)';ctx.beginPath();ctx.moveTo(i*38+Math.sin(t*.3)*7,0);ctx.lineTo(i*38+15,0);ctx.lineTo(i*38-22,220);ctx.lineTo(i*38-48,220);ctx.fill();}
for(let i=0;i<32;i++){ctx.fillStyle=i%2?'#89e0de55':'#c6f4e044';ctx.fillRect((i*37+Math.sin(t+i)*3)%240,8+(i%5)*5,8+i%9,2);}
// Terraced rocks, sand and underwater plants.
ctx.fillStyle='#14617a';ctx.fillRect(0,182,240,38);ctx.fillStyle='#877c65';ctx.fillRect(0,210,240,10);
for(let side=0;side<2;side++)for(let i=0;i<5;i++){const x=side?218-i*5:-9+i*3,y=135+i*15;ctx.fillStyle=i%2?'#355f6b':'#456f74';ctx.fillRect(x,y,27,14);ctx.fillStyle='#7e9c8a';ctx.fillRect(x,y,25,3);}
for(let i=0;i<17;i++){const x=(i*29)%240,y=191+(i%3)*7;ctx.fillStyle=i%3?'#279b8e':'#60ba8c';ctx.fillRect(x,y-18-i%19,3,39);ctx.fillRect(x-4,y-12,5,3);ctx.fillRect(x+2,y-23,5,3);}
for(let i=0;i<6;i++){const x=8+i*45,y=204-i%3*6;ctx.fillStyle=i%2?'#d38496':'#d8aa68';ctx.fillRect(x,y-12,3,21);ctx.fillRect(x-5,y-6,12,3);ctx.fillRect(x-5,y-12,3,7);ctx.fillRect(x+5,y-17,3,12);}
state.fish.slice(0,40).forEach((id,i)=>{const phase=(i*47+t*(7+i%4))%370;const right=phase<185;const x=26+(right?phase:370-phase),y=58+(i*29)%104+Math.sin(t*.7+i)*3;ctx.save();ctx.translate(Math.round(x),Math.round(y));if(!right)ctx.scale(-1,1);

const palettes=[['#354f43','#879d6e','#e4e9cf'],['#153d62','#55afc1','#d2eef0'],['#423353','#a080ac','#eeddd7'],['#25503e','#76a877','#deebbc'],['#735020','#d7ad52','#fff2ce']];
const pal=palettes[id]||palettes[0],sway=Math.sin(t*4+i)*2;
ctx.fillStyle='#04374733';ctx.beginPath();ctx.ellipse(0,13,19,2,0,0,Math.PI*2);ctx.fill();
function fin(points){ctx.fillStyle=pal[1];ctx.beginPath();points.forEach(([x,y],j)=>j?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
ctx.globalAlpha=.75;fin([[-12,0],[-23,-9+sway],[-20,sway],[-23,9+sway]]);fin([[-7,-3],[-4,-11],[2,-9],[8,-4]]);fin([[-1,5],[3,11],[10,8],[9,4]]);ctx.globalAlpha=1;
const body=ctx.createLinearGradient(0,-7,0,8);body.addColorStop(0,pal[0]);body.addColorStop(.35,pal[1]);body.addColorStop(.7,pal[1]);body.addColorStop(1,pal[2]);
ctx.fillStyle=body;ctx.beginPath();ctx.moveTo(-14,0);ctx.bezierCurveTo(-7,-9,10,-10,18,-3);ctx.quadraticCurveTo(22,-1,21,1);ctx.quadraticCurveTo(18,9,3,8);ctx.bezierCurveTo(-7,8,-10,4,-14,0);ctx.fill();ctx.strokeStyle=pal[0];ctx.lineWidth=.6;ctx.stroke();
ctx.save();ctx.beginPath();ctx.ellipse(0,0,13,6,0,0,Math.PI*2);ctx.clip();
for(let row=0;row<5;row++)for(let col=0;col<9;col++){const x=-11+col*2.8+(row%2)*1.4,y=-5+row*2.2;ctx.strokeStyle=row<2?'#173e424d':'#eff7ce55';ctx.lineWidth=.45;ctx.beginPath();ctx.arc(x,y,1.5,-.7,.7);ctx.stroke();}
if(id===0){ctx.fillStyle='#293f46aa';for(let j=0;j<12;j++){ctx.beginPath();ctx.arc(-9+(j*7)%20,-3+(j*3)%6,.6,0,Math.PI*2);ctx.fill();}}
ctx.restore();ctx.strokeStyle=pal[0];ctx.lineWidth=.75;ctx.beginPath();ctx.moveTo(12,-4);ctx.quadraticCurveTo(8,1,12,6);ctx.stroke();
ctx.globalAlpha=.7;fin([[3,1],[6,3],[2,8+sway*.5],[-1,6]]);ctx.globalAlpha=1;
ctx.strokeStyle='#eaf1cb77';ctx.lineWidth=.45;for(let j=0;j<3;j++){ctx.beginPath();ctx.moveTo(-13,0);ctx.lineTo(-21,(-6+j*6)+sway);ctx.stroke();}
ctx.fillStyle='#dece99';ctx.beginPath();ctx.arc(16,-2,2.2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#122731';ctx.beginPath();ctx.arc(16.5,-2,1.2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(17,-2.6,.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle=pal[0];ctx.beginPath();ctx.moveTo(18,3);ctx.lineTo(21,2);ctx.stroke();
ctx.restore();});
ctx.fillStyle='#9ee4de88';for(let i=0;i<12;i++){const x=i*21+Math.sin(t+i)*2,y=210-((t*7+i*19)%175);ctx.strokeStyle='#a6e7e466';ctx.strokeRect(Math.round(x),Math.round(y),3,3);}if(!reduced)requestAnimationFrame(draw);}draw(0);

let session=null;
function openRiver(){if(session)return;const selectedZone=zone;const el=document.createElement('section');el.className='river-overlay';el.innerHTML='<div class="river-screen"><header><span class="eyebrow">PESCA ACTIVA</span><div class="river-heading"><h2>Río tranquilo</h2><button id="exit">Salir ✕</button></div></header><canvas id="river" width="270" height="260" aria-label="Pescador con caña junto al río"></canvas><div class="river-controls"><h3 id="title">Prepara tu caña</h3><p id="message"></p><div id="combat" hidden><div class="fight-track"><div id="zone"></div><span id="marker" aria-label="Pez"><svg viewBox="0 0 40 24" aria-hidden="true"><path fill="#8eaa79" stroke="#334d44" d="M9 5Q22-3 34 7L38 10L35 16Q21 27 9 18L2 22L3 3Z"/><path fill="#dce5b6" d="M10 14Q24 23 34 14L33 18Q20 24 10 18Z"/><path fill="#658769" d="M16 5L20 0L24 5M16 18L20 24L25 19"/><circle cx="30" cy="9" r="4" fill="#f7efd3"/><circle cx="31" cy="9" r="2" fill="#20313c"/></svg></span></div><label>Progreso de captura<progress id="progress" max="100" value="35"></progress></label></div><button id="tap">Tirar anzuelo</button></div></div>';document.body.append(el);document.body.classList.add('river-open');session={phase:'ready',timer:0,raf:0,id:0};const q=id=>el.querySelector('#'+id);q('message').textContent=state.baits[selectedZone]+' cebos disponibles';el.querySelector('h2').textContent=zones[selectedZone].name;q('exit').onclick=()=>{clearTimeout(session.timer);cancelAnimationFrame(session.raf);session=null;el.remove();document.body.classList.remove('river-open');render();};const r=q('river').getContext('2d');function scene(){r.fillStyle='#6dbb58';r.fillRect(0,0,270,260);r.fillStyle=zones[selectedZone].color;r.fillRect(185,0,48,260);r.fillRect(0,108,230,24);r.fillStyle='#8bd8c9';for(let i=0;i<18;i++)r.fillRect(192+i%3*12,i*17,8,2);r.fillStyle='#d7ae79';r.fillRect(22,155,20,77);r.fillRect(22,215,120,17);r.fillRect(30,60,171,17);r.fillRect(18,65,25,39);r.fillStyle='#b78353';function bridge(x,y,w,h){r.fillRect(x,y,w,h);r.fillStyle='#e1b784';for(let i=0;i<w;i+=9)r.fillRect(x+i,y+2,7,h-4);r.fillStyle='#806041';r.fillRect(x-3,y-3,w+6,3);r.fillRect(x-3,y+h,w+6,3);}bridge(173,58,68,18);bridge(18,104,25,33);bridge(178,197,63,18);function tree(x,y){r.fillStyle='#78563e';r.fillRect(x+8,y+14,5,12);r.fillStyle='#317b48';r.fillRect(x,y+3,24,18);r.fillStyle='#4d9b4e';r.fillRect(x+3,y,18,18);r.fillStyle='#7ab956';r.fillRect(x+6,y+2,10,6);}[[48,136],[73,136],[98,136],[143,85],[151,229],[119,230],[63,237],[7,235],[10,12],[44,14],[110,8],[244,36]].forEach(([x,y])=>tree(x,y));r.fillStyle='#96a8a5';r.fillRect(136,208,13,8);r.fillStyle='#d2d6be';r.fillRect(138,205,8,5);r.fillStyle='#eff0bb';for(let i=0;i<11;i++)r.fillRect(i*37%175,25+i*19,2,2);
// Original top-down angler at the riverbank.
r.fillStyle='#23354b';r.fillRect(153,167,6,8);r.fillRect(162,167,6,8);r.fillStyle='#ca6854';r.fillRect(152,158,17,11);r.fillStyle='#ecc099';r.fillRect(155,148,12,12);r.fillStyle='#3e2d35';r.fillRect(153,145,16,6);r.fillRect(153,150,4,5);r.fillStyle='#263246';r.fillRect(163,153,2,2);r.strokeStyle='#78563c';r.lineWidth=2;r.beginPath();r.moveTo(166,164);r.lineTo(187,150);r.stroke();if(['waiting','bite','fight'].includes(session.phase)){r.strokeStyle='#fff4d6';r.lineWidth=1;r.beginPath();r.moveTo(187,150);r.lineTo(207,181);r.stroke();r.fillStyle='#fff';r.fillRect(204,178,6,7);r.fillStyle='#e87860';r.fillRect(204,182,6,3);if(session.phase==='bite'){r.fillStyle='#fff1b6';r.font='bold 16px monospace';r.fillText('!',201,171);}}
}

function label(title,msg,button){q('title').textContent=title;q('message').textContent=msg;q('tap').textContent=button;}
function finish(won){session.held=false;el.classList.remove('is-fighting');session.phase='result';q('combat').hidden=true;q('tap').disabled=false;if(won){state=accrue(state);state.fish.push(session.id);save();const f=species[session.id];const card=document.createElement('div');card.className='catch-card';card.innerHTML='<small>CAPTURA CONSEGUIDA</small><strong>'+f.name+'</strong><span>'+f.rarity+' · +'+f.rate+' CASH / día</span><button>Continuar</button>';el.append(card);card.querySelector('button').onclick=()=>card.remove();label('¡Captura conseguida!',f.name+' · '+f.rarity+' · +'+f.rate+' CASH/día','Tirar otra vez');}else label('El pez escapó','El intento consumió un cebo. Prueba otra vez.','Tirar otra vez');scene();}
function loop(now){if(!session||session.phase!=='fight')return;const dt=Math.min((now-session.last)/1000,.05);session.last=now;session.time+=dt;const pos=.5+.36*Math.sin(session.time*[0.85,1.15,1.45,1.0,1.7][session.id]*zones[selectedZone].speed)+.04*Math.sin(session.time*2);session.v+=(session.held?1.6:-1.35)*dt;session.v=Math.max(-.65,Math.min(.65,session.v));session.green=Math.max(.14,Math.min(.86,session.green+session.v*dt));if(session.green===.14||session.green===.86)session.v=0;const inside=Math.abs(pos-session.green)<=.14;session.progress=Math.max(0,Math.min(100,session.progress+(inside?23:-15)*dt));q('zone').style.bottom=((session.green-.14)*100)+'%';q('marker').style.bottom=pos*100+'%';q('progress').value=session.progress;q('combat').style.setProperty('--capture',session.progress+'%');q('zone').classList.toggle('inside',inside);if(session.progress>=100)return finish(true);if(session.progress<=0||session.time>30)return finish(false);session.raf=requestAnimationFrame(loop);}
const control=q('tap');function release(){if(session)session.held=false;control.classList.remove('pressed');}control.addEventListener('pointerdown',e=>{if(session?.phase==='fight'){e.preventDefault();session.held=true;control.classList.add('pressed');control.setPointerCapture(e.pointerId);}});control.addEventListener('pointerup',release);control.addEventListener('pointercancel',release);control.addEventListener('lostpointercapture',release);window.addEventListener('blur',release,{signal:(()=>{const controller=new AbortController();const previous=q('exit').onclick;q('exit').onclick=()=>{controller.abort();previous();};return controller.signal;})()});control.addEventListener('keydown',e=>{if(session?.phase==='fight'&&(e.code==='Space'||e.code==='Enter')){e.preventDefault();session.held=true;}});control.addEventListener('keyup',release);
q('tap').onclick=()=>{if(session.phase==='fight')return;if(session.phase==='waiting')return;if(session.phase==='bite'){clearTimeout(session.timer);Object.assign(session,{phase:'fight',green:.22,v:0,held:false,progress:35,time:0,last:performance.now()});q('combat').hidden=false;el.classList.add('is-fighting');label('¡Combate!','Mantén el dedo apoyado en el botón para subir la zona verde; levántalo para bajarla. Mantén al pez dentro hasta llenar la barra lateral.','Mantén para recoger');session.raf=requestAnimationFrame(loop);return;}if(state.baits[selectedZone]<1){label('Sin cebos','Sal y compra cebos en la tienda.','Tirar anzuelo');return;}state.baits[selectedZone]--;save();session.id=rollFish(selectedZone);session.phase='waiting';label('Anzuelo en el agua','Espera la picada… · '+state.baits[selectedZone]+' cebos restantes','Esperando…');q('tap').disabled=true;scene();session.timer=setTimeout(()=>{if(!session)return;session.phase='bite';label('¡Ha picado!','Pulsa Capturar antes de que escape.','Capturar');q('tap').disabled=false;scene();session.timer=setTimeout(()=>{if(session?.phase==='bite')finish(false);},5000);},1800+Math.random()*2400);};scene();}


