import {initial,accrue,cast,collect,claimDaily,species} from './engine.js';
const $=id=>document.getElementById(id);const key='laguna-pixel-v1';let state=initial(),tab='fish';try{const s=JSON.parse(localStorage.getItem(key));if(s?.version===1&&['fin','cash','pending','last'].every(k=>Number.isFinite(s[k])&&s[k]>=0)&&Array.isArray(s.fish)&&s.fish.every(i=>Number.isInteger(i)&&species[i]))state=s;}catch{}
state.bait=Number.isInteger(state.bait)&&state.bait>=0?state.bait:0;
const fmt=n=>n.toLocaleString('es',{maximumFractionDigits:2});function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('status').textContent='El navegador no permite guardar. Tu progreso durará esta sesión.';}}function update(){state=accrue(state);$('fin').textContent=fmt(state.fin);$('cash').textContent=fmt(state.cash);$('pending').textContent=fmt(state.pending);$('production').textContent=fmt(state.fish.reduce((n,i)=>n+species[i].rate,0))+' CASH / día';$('collection').disabled=state.pending<=0;}
function render(){update();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const panel=$('panel');if(tab==='fish'){panel.innerHTML='<h2>Vamos al río</h2><p>'+state.bait+' cebos disponibles. Tira, espera la picada y combate para capturar.</p><button id="go">Ir al río</button>';$('go').onclick=openRiver;}else if(tab==='shop'){panel.innerHTML='<h2>Tienda de cebos</h2><p>Cada intento consume un cebo, aunque el pez escape.</p><div class="cards">'+[1,5,11].map(n=>`<button data-buy="${n}">${n} cebos<small>${fmt(n===11?13000:n*1300)} FIN</small></button>`).join('')+'</div>';panel.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>action(()=>{const n=+b.dataset.buy,cost=n===11?13000:n*1300;if(state.fin<cost)throw Error('FIN insuficientes');state.fin-=cost;state.bait+=n;return 'Compraste '+n+' cebos.';}));}else if(tab==='inventory'){panel.innerHTML='<h2>Tu colección</h2>'+species.map((f,i)=>{const n=state.fish.filter(j=>j===i).length;return `<div class="row"><span>${f.name} ×${n}<small>${f.rarity} · ${f.rate} CASH por pez/día</small></span><strong>${n*f.rate} / día</strong></div>`}).join('');}else if(tab==='tasks'){panel.innerHTML='<h2>Tarea diaria</h2><p>Vuelve cada día para recibir 1,300 FIN de prueba. El día se renueva a las 00:00 UTC.</p><button id="daily">Recoger recompensa</button>';$('daily').disabled=state.daily===new Date().toISOString().slice(0,10);$('daily').onclick=()=>action(()=>{state=claimDaily(state);return 'Recibiste 1,300 FIN.';});}else{panel.innerHTML='<h2>Billetera de prueba</h2><p>Saldo: <strong>'+fmt(state.cash)+' CASH</strong></p><p class="notice">Esta demo no acepta depósitos ni procesa retiros. Los saldos se guardan en este dispositivo y no tienen valor monetario.</p>';}}
function action(fn){try{const message=fn();save();render();$('status').textContent=message;}catch(e){$('status').textContent=e.message;}}
$('collection').onclick=()=>action(()=>{state=collect(state);return 'CASH acumulado recogido.';});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});render();setInterval(()=>{update();save();},1000);
const canvas=$('water'),ctx=canvas.getContext('2d');canvas.width=240;canvas.height=220;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function draw(time){const t=reduced?0:time/1000;const g=ctx.createLinearGradient(0,0,0,220);g.addColorStop(0,'#43c4cf');g.addColorStop(.35,'#118cb5');g.addColorStop(1,'#073f6d');ctx.fillStyle=g;ctx.fillRect(0,0,240,220);
// Shifting surface ripples and sunlight shafts.
for(let i=0;i<8;i++){ctx.fillStyle='rgba(163,247,232,.055)';ctx.beginPath();ctx.moveTo(i*38+Math.sin(t*.3)*7,0);ctx.lineTo(i*38+15,0);ctx.lineTo(i*38-22,220);ctx.lineTo(i*38-48,220);ctx.fill();}
for(let i=0;i<32;i++){ctx.fillStyle=i%2?'#89e0de55':'#c6f4e044';ctx.fillRect((i*37+Math.sin(t+i)*3)%240,8+(i%5)*5,8+i%9,2);}
// Terraced rocks, sand and underwater plants.
ctx.fillStyle='#14617a';ctx.fillRect(0,182,240,38);ctx.fillStyle='#877c65';ctx.fillRect(0,210,240,10);
for(let side=0;side<2;side++)for(let i=0;i<5;i++){const x=side?218-i*5:-9+i*3,y=135+i*15;ctx.fillStyle=i%2?'#355f6b':'#456f74';ctx.fillRect(x,y,27,14);ctx.fillStyle='#7e9c8a';ctx.fillRect(x,y,25,3);}
for(let i=0;i<17;i++){const x=(i*29)%240,y=191+(i%3)*7;ctx.fillStyle=i%3?'#279b8e':'#60ba8c';ctx.fillRect(x,y-18-i%19,3,39);ctx.fillRect(x-4,y-12,5,3);ctx.fillRect(x+2,y-23,5,3);}
for(let i=0;i<6;i++){const x=8+i*45,y=204-i%3*6;ctx.fillStyle=i%2?'#d38496':'#d8aa68';ctx.fillRect(x,y-12,3,21);ctx.fillRect(x-5,y-6,12,3);ctx.fillRect(x-5,y-12,3,7);ctx.fillRect(x+5,y-17,3,12);}
state.fish.slice(0,40).forEach((id,i)=>{const phase=(i*47+t*(7+i%4))%370;const right=phase<185;const x=26+(right?phase:370-phase),y=58+(i*29)%104+Math.sin(t*.7+i)*3;ctx.save();ctx.translate(Math.round(x),Math.round(y));if(!right)ctx.scale(-1,1);ctx.fillStyle='#033f6566';ctx.fillRect(-8,13,23,3);ctx.fillStyle='#263f50';ctx.fillRect(-7,-4,19,12);ctx.fillRect(-10,-1,25,6);ctx.fillStyle=species[id].color;ctx.fillRect(-7,-3,18,10);ctx.fillRect(-9,0,23,4);ctx.fillRect(-14,-3,4,10);ctx.fillRect(-11,0,3,4);ctx.fillStyle='#fff2cb';ctx.fillRect(-4,4,12,3);ctx.fillStyle='#ad7e48';ctx.fillRect(-4,-6,7,3);ctx.fillRect(-5,0,2,2);ctx.fillRect(0,-2,2,2);ctx.fillStyle='#fff';ctx.fillRect(7,-3,5,5);ctx.fillStyle='#213248';ctx.fillRect(10,-2,2,3);ctx.fillStyle='#bd765b';ctx.fillRect(12,3,3,2);ctx.restore();});
ctx.fillStyle='#9ee4de88';for(let i=0;i<12;i++){const x=i*21+Math.sin(t+i)*2,y=210-((t*7+i*19)%175);ctx.strokeStyle='#a6e7e466';ctx.strokeRect(Math.round(x),Math.round(y),3,3);}if(!reduced)requestAnimationFrame(draw);}draw(0);

let session=null;
function openRiver(){if(session)return;const el=document.createElement('section');el.className='river-overlay';el.innerHTML='<div class="river-screen"><header><span class="eyebrow">PESCA ACTIVA</span><div class="river-heading"><h2>Río tranquilo</h2><button id="exit">Salir ✕</button></div></header><canvas id="river" width="270" height="260" aria-label="Pescador con caña junto al río"></canvas><div class="river-controls"><h3 id="title">Prepara tu caña</h3><p id="message"></p><div id="combat" hidden><div class="fight-track"><div id="zone"></div><span id="marker">◆</span></div><label>Progreso de captura<progress id="progress" max="100" value="35"></progress></label></div><button id="tap">Tirar anzuelo</button></div></div>';document.body.append(el);document.body.classList.add('river-open');session={phase:'ready',timer:0,raf:0,id:0};const q=id=>el.querySelector('#'+id);q('message').textContent=state.bait+' cebos disponibles';q('exit').onclick=()=>{clearTimeout(session.timer);cancelAnimationFrame(session.raf);session=null;el.remove();document.body.classList.remove('river-open');render();};const r=q('river').getContext('2d');function scene(){r.fillStyle='#a7d9d0';r.fillRect(0,0,270,260);for(let i=0;i<7;i++){r.fillStyle='#386b56';r.fillRect(i*45,38,30,61);r.fillStyle='#61996c';r.fillRect(i*45-5,24,40,37);}r.fillStyle='#248fae';r.fillRect(0,99,270,161);r.fillStyle='#77cbd0';for(let i=0;i<20;i++)r.fillRect(i*47%260,112+i*7,18,2);r.fillStyle='#65935b';r.fillRect(0,122,72,138);r.fillStyle='#c3ad78';r.fillRect(52,145,34,115);r.fillStyle='#886645';r.fillRect(40,154,70,8);r.fillRect(40,165,70,5);r.fillStyle='#223247';r.fillRect(57,133,7,20);r.fillRect(70,133,7,20);r.fillStyle='#e8b482';r.fillRect(59,99,17,17);r.fillStyle='#f0ce76';r.fillRect(54,96,28,6);r.fillRect(60,89,16,9);r.fillStyle='#d26f5b';r.fillRect(56,116,24,18);r.fillStyle='#e8b482';r.fillRect(78,118,12,5);r.strokeStyle='#684b32';r.lineWidth=2;r.beginPath();r.moveTo(86,122);r.lineTo(126,80);r.stroke();if(['waiting','bite','fight'].includes(session.phase)){r.strokeStyle='#eef7dd';r.lineWidth=1;r.beginPath();r.moveTo(126,80);r.lineTo(184,166);r.stroke();r.fillStyle='#fff3ce';r.fillRect(181,160,6,10);r.fillStyle='#e56854';r.fillRect(181,165,6,4);if(session.phase==='bite'){r.strokeStyle='#fff';r.strokeRect(174,156,20,20);}}}
function label(title,msg,button){q('title').textContent=title;q('message').textContent=msg;q('tap').textContent=button;}
function finish(won){session.phase='result';q('combat').hidden=true;q('tap').disabled=false;if(won){state=accrue(state);state.fish.push(session.id);save();const f=species[session.id];label('¡Captura conseguida!',f.name+' · '+f.rarity+' · +'+f.rate+' CASH/día','Tirar otra vez');}else label('El pez escapó','El intento consumió un cebo. Prueba otra vez.','Tirar otra vez');scene();}
function loop(now){if(!session||session.phase!=='fight')return;const dt=Math.min((now-session.last)/1000,.05);session.last=now;session.time+=dt;const pos=.5+.36*Math.sin(session.time*[1.6,2.2,2.8][session.id])+.07*Math.sin(session.time*4);session.v-=.65*dt;session.green=Math.max(.14,Math.min(.86,session.green+session.v*dt));if(session.green===.14||session.green===.86)session.v=0;const inside=Math.abs(pos-session.green)<=.14;session.progress=Math.max(0,Math.min(100,session.progress+(inside?23:-15)*dt));q('zone').style.left=((session.green-.14)*100)+'%';q('marker').style.left=pos*100+'%';q('progress').value=session.progress;q('zone').classList.toggle('inside',inside);if(session.progress>=100)return finish(true);if(session.progress<=0||session.time>30)return finish(false);session.raf=requestAnimationFrame(loop);}
q('tap').onclick=()=>{if(session.phase==='fight'){session.v=Math.min(1.1,session.v+.32);return;}if(session.phase==='waiting')return;if(session.phase==='bite'){clearTimeout(session.timer);Object.assign(session,{phase:'fight',green:.5,v:0,progress:35,time:0,last:performance.now()});q('combat').hidden=false;label('¡Combate!','Toca para mover la zona verde a la derecha. Al soltar, retrocede. Mantén el pez dentro hasta llenar la barra.','TAP · Mantener en verde');session.raf=requestAnimationFrame(loop);return;}if(state.bait<1){label('Sin cebos','Sal y compra cebos en la tienda.','Tirar anzuelo');return;}state.bait--;save();const roll=Math.random();session.id=roll<.8?0:roll<.95?1:2;session.phase='waiting';label('Anzuelo en el agua','Espera la picada… · '+state.bait+' cebos restantes','Esperando…');q('tap').disabled=true;scene();session.timer=setTimeout(()=>{if(!session)return;session.phase='bite';label('¡Ha picado!','Pulsa Capturar antes de que escape.','Capturar');q('tap').disabled=false;scene();session.timer=setTimeout(()=>{if(session?.phase==='bite')finish(false);},5000);},1800+Math.random()*2400);};scene();}
