import {financeOnline} from './online-client.js?v=admin-test-37';
const fmt=n=>Number(n).toLocaleString('es',{maximumFractionDigits:9});
const labels={pending:'Pendiente',paid:'Pagado',rejected:'Rechazado'};
export function mountWallet(panel,onRefresh){
 panel.innerHTML='<h2>Billetera</h2><p id="wallet-info">Consultando cuenta…</p><div class="cards"><button id="wallet-deposit">Depositar</button><button id="wallet-withdraw">Retirar</button></div><label>Moneda · red TON<select id="wallet-network"><option value="ton">TON (Gram)</option><option value="usdt">USDT en TON</option></select></label><div id="wallet-form"></div><p id="wallet-result" role="status"></p><div id="wallet-history"></div><div id="wallet-admin"></div>';
 const q=id=>panel.querySelector('#'+id);let mode='deposit',account=null;
 const error=e=>{if(q('wallet-result'))q('wallet-result').textContent=e.message;};
 async function busy(button,fn){button.disabled=true;try{await fn();}catch(e){error(e);}finally{if(button.isConnected)button.disabled=false;}}
 async function refresh(){account=await financeOnline('wallet');if(!panel.isConnected)return;q('wallet-info').textContent='Tu ID de Telegram: '+account.playerId+' · '+fmt(Number(account.balances.cash_micros)/1e6)+' CASH disponibles · '+fmt(Number(account.balances.held_cash_micros)/1e6)+' CASH reservados.';
  q('wallet-history').replaceChildren();for(const d of account.deposits){const b=document.createElement('button');b.textContent='Recarga '+fmt(d.view_amount)+' VIEW · '+labels[d.status];b.onclick=()=>showOrder({...d,memo:'AquaView:'+d.id,destination:'UQAGxytQ9Fk1yo8N7ilb_AL39wsmeTOehefvVCpfDf4oA1Mt'});q('wallet-history').append(b);}for(const w of account.withdrawals){const p=document.createElement('p');p.textContent='Retiro '+fmt(Number(w.net_units)/(w.network==='ton'?1e9:1e6))+' '+w.network.toUpperCase()+' · '+labels[w.status];q('wallet-history').append(p);}if(account.admin)await admin();}
 function paint(){const requestId=crypto.randomUUID(),operation=mode;const network=q('wallet-network').value,ton=network==='ton',min=ton?.1:1,unit=ton?'TON':'USDT';q('wallet-form').innerHTML='<h3>'+(mode==='deposit'?'Recargar VIEW':'Solicitar retiro de CASH')+'</h3><label>Importe en '+unit+'<input id="wallet-amount" type="number" min="'+min+'" step="'+(ton?.1:1)+'" value="'+min+'"></label><input id="wallet-slider" type="range" aria-label="Ajustar importe" min="'+min+'" max="'+(ton?100:500)+'" step="'+min+'" value="'+min+'"><p id="wallet-quote"></p>'+(mode==='withdraw'?'<label>Dirección de destino · TON<input id="wallet-address" autocomplete="off" spellcheck="false" maxlength="48"></label><p>Comisión del 5%. El envío se revisa y procesa manualmente; puedes consultar su estado aquí.</p>':'<p>Envía únicamente la moneda seleccionada en la red TON, con el comentario del pedido. La comisión de red se paga aparte. No uses BEP-20 ni TRC-20.</p>')+'<button id="wallet-submit">'+(mode==='deposit'?'Crear pedido de recarga':'Solicitar retiro')+'</button>';const calculate=()=>{const a=Number(q('wallet-amount').value),rate=ton?13000:10000;q('wallet-quote').textContent=mode==='deposit'?fmt(a)+' '+unit+' → '+fmt(a*rate)+' VIEW':fmt(a*rate)+' CASH → recibes '+fmt(a*.95)+' '+unit+' (comisión '+fmt(a*.05)+' '+unit+').';};q('wallet-slider').oninput=()=>{q('wallet-amount').value=q('wallet-slider').value;calculate();};q('wallet-amount').oninput=calculate;calculate();const submit=q('wallet-submit');submit.disabled=!account?.enabled;submit.onclick=()=>busy(submit,async()=>{const data=await financeOnline(mode==='deposit'?'deposit':'withdraw',{requestId,network,amount:q('wallet-amount').value,...(mode==='withdraw'?{address:q('wallet-address').value.trim()}:{})});if(operation==='deposit')showOrder(data);else{q('wallet-result').textContent='Retiro solicitado. El CASH quedó reservado hasta procesar el envío.';await onRefresh();}await refresh();});if(account&&!account.enabled)q('wallet-result').textContent='Los depósitos y retiros están pendientes de activación por el administrador.';}
 function showOrder(d){if(d.status==='paid'){q('wallet-form').innerHTML='<h3>Recarga confirmada</h3><p>Este pedido ya fue acreditado. Crea un pedido nuevo para otra recarga.</p>';return;}const unit=d.network==='ton'?'TON':'USDT',amount=Number(d.units)/(d.network==='ton'?1e9:1e6);q('wallet-form').innerHTML='<h3>Pedido de recarga</h3><p id="order-description"></p><label>Dirección receptora<input id="order-address" readonly></label><label>Comentario obligatorio<input id="order-memo" readonly></label><button id="order-copy">Copiar comentario</button><label>Hash de la transacción<input id="order-hash" placeholder="64 caracteres hexadecimales" maxlength="64" autocomplete="off"></label><button id="order-verify">Verificar depósito</button><p>Tras enviar, espera al menos 30 segundos. Conserva el pedido hasta que se acredite. Puedes abrirlo de nuevo en el historial.</p>';q('order-description').textContent='Envía exactamente '+fmt(amount)+' '+unit+' en TON. Recibirás '+fmt(d.view_amount)+' VIEW.';q('order-address').value=d.destination;q('order-memo').value=d.memo;q('order-copy').onclick=()=>busy(q('order-copy'),async()=>{await navigator.clipboard.writeText(d.memo);q('wallet-result').textContent='Comentario copiado.';});q('order-verify').disabled=d.status==='paid';q('order-verify').onclick=()=>busy(q('order-verify'),async()=>{await financeOnline('verify',{orderId:d.id,hash:q('order-hash').value.trim()});q('wallet-result').textContent='Depósito confirmado. VIEW acreditados.';await onRefresh();await refresh();});}
 async function admin(){const data=await financeOnline('admin');q('wallet-admin').replaceChildren();const title=document.createElement('h3');title.textContent='Administración de retiros';q('wallet-admin').append(title);for(const w of data.withdrawals){const row=document.createElement('section'),p=document.createElement('p'),input=document.createElement('input'),paid=document.createElement('button'),reject=document.createElement('button');p.textContent='Cuenta '+w.player_id+' · Envía '+fmt(Number(w.net_units)/(w.network==='ton'?1e9:1e6))+' '+w.network.toUpperCase()+' a '+w.destination+' · Comentario: AquaView:withdraw:'+w.id;input.placeholder='Hash del envío realizado';paid.textContent='Comprobar pago';reject.textContent='Rechazar y devolver CASH';paid.onclick=()=>busy(paid,async()=>{await financeOnline('admin/paid',{requestId:w.id,hash:input.value.trim()});await refresh();});reject.onclick=()=>{if(!confirm('¿Rechazar este retiro? Confirma que no has enviado el pago.'))return;void busy(reject,async()=>{await financeOnline('admin/reject',{requestId:w.id,playerId:String(w.player_id)});await refresh();});};row.append(p,input,paid,reject);q('wallet-admin').append(row);}}
 q('wallet-deposit').onclick=()=>{mode='deposit';paint();};q('wallet-withdraw').onclick=()=>{mode='withdraw';paint();};q('wallet-network').onchange=paint;void refresh().then(paint).catch(error);
}
