import test from 'node:test';import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';import {Finance} from './finance.js';import {GroupTask} from './group-task.js';
test('group reward validates membership, handles errors and credits only once per authenticated account',async()=>{
 const db=new PGlite();let gate=Promise.resolve();const pool={query:(...a)=>db.query(...a),async connect(){const old=gate;let release;gate=new Promise(r=>release=r);await old;return {query:(...a)=>db.query(...a),release};}};
 try{await db.query('CREATE TABLE players(id BIGINT PRIMARY KEY)');for(const id of [123,456,789])await db.query('INSERT INTO players VALUES($1)',[id]);const finance=new Finance(pool);await finance.init();let status='left',bad=false,wrong=false,calls=0;const task=new GroupTask(finance,{token:'TEST_TOKEN',chatId:'-100123456',fetcher:async(url,options)=>{calls++;assert.ok(url.endsWith('/getChatMember'));const body=JSON.parse(options.body);assert.equal(body.chat_id,'-100123456');return {ok:!bad,json:async()=>({ok:!bad,result:{user:{id:wrong?999:body.user_id},status,is_member:status==='restricted'}})};}});await task.init();
 await assert.rejects(()=>task.claim('123'),/Únete/);status='kicked';await assert.rejects(()=>task.claim('123'));status='member';bad=true;await assert.rejects(()=>task.claim('123'),/No se pudo/);bad=false;wrong=true;await assert.rejects(()=>task.claim('123'));wrong=false;
 assert.equal(String((await finance.balances('123')).view_balance),'0');
 const results=await Promise.all([task.claim('123'),task.claim('123')]);assert.equal(results.filter(x=>x.credited).length,1);assert.equal(String((await finance.balances('123')).view_balance),'200');assert.equal(String((await finance.balances('123')).cash_micros),'0');status='left';const before=calls;assert.equal((await task.claim('123')).credited,false);assert.equal(calls,before);assert.equal((await task.status('123')).claimed,true);
 status='restricted';assert.equal((await task.claim('456')).credited,true);status='creator';assert.equal((await task.claim('789')).credited,true);assert.equal((await db.query("SELECT count(*) AS n FROM finance_events WHERE kind='group_task'")).rows[0].n,3);
 const missing=new GroupTask(finance,{token:'TEST',chatId:''});assert.equal((await missing.status('456')).configured,false);await db.query('INSERT INTO players VALUES(999)');await assert.rejects(()=>missing.claim('999'),/configuración/);
 }finally{await db.close();}
});
test('group discovery exposes only metadata from administrator updates without consuming the bot queue',async()=>{
 const task=new GroupTask(null,{token:'TEST',fetcher:async(url,options)=>{assert.ok(url.endsWith('/getUpdates'));assert.deepEqual(JSON.parse(options.body),{limit:100,timeout:0});return {ok:true,json:async()=>({ok:true,result:[{message:{from:{id:123},chat:{id:-1001,type:'supergroup',title:'Aqua View'},text:'Private content not returned'}},{message:{from:{id:456},chat:{id:-1002,type:'supergroup',title:'Other group'}}},{my_chat_member:{from:{id:123},chat:{id:-1001,type:'supergroup',title:'Aqua View'}}}]})};}});assert.deepEqual(await task.discover('123'),[{id:'-1001',title:'Aqua View'}]);
});
