import pg from 'pg';
import {fileURLToPath} from 'node:url';
import {Store} from './store.js';
import {makeServer} from './http.js';
import {Chain} from './chain.js';
import {CryptoFinance} from './crypto-finance.js';
const {BOT_TOKEN,DATABASE_URL,APP_URL,RENDER_EXTERNAL_URL,PORT='3000'}=process.env;
if(!BOT_TOKEN||!DATABASE_URL)throw Error('Configura BOT_TOKEN y DATABASE_URL en el servidor.');
const pool=new pg.Pool({connectionString:DATABASE_URL,max:10,connectionTimeoutMillis:10000});
pool.on('error',e=>console.error('Database error:',e.code));
const finance=new CryptoFinance(pool,new Chain(process.env.TONAPI_KEY));
const store=new Store(pool,{finance,official:true});await store.init();await finance.init();
const adminId=process.env.ADMIN_TELEGRAM_ID||'';
if(adminId&&!/^[1-9]\d{0,15}$/.test(adminId))throw Error('ADMIN_TELEGRAM_ID debe ser el ID numérico de Telegram.');
const server=makeServer({store,finance,adminId,paymentsEnabled:process.env.PAYMENTS_ENABLED==='true',botToken:BOT_TOKEN,root:fileURLToPath(new URL('../',import.meta.url)),appUrl:APP_URL||RENDER_EXTERNAL_URL});
server.listen(Number(PORT),'0.0.0.0',()=>console.log('Aqua View online: ready'));
process.on('SIGTERM',()=>server.close(()=>pool.end().finally(()=>process.exit(0))));
