import {randomUUID} from 'node:crypto';
export class Referrals {
 constructor(finance){this.finance=finance;}
 async init(){const schema=`
 CREATE TABLE IF NOT EXISTS referral_accounts(player_id BIGINT PRIMARY KEY REFERENCES players(id),pending_micros NUMERIC(30,0) NOT NULL DEFAULT 0 CHECK(pending_micros>=0),total_micros NUMERIC(30,0) NOT NULL DEFAULT 0 CHECK(total_micros>=0));
 CREATE TABLE IF NOT EXISTS referral_rewards(reference TEXT PRIMARY KEY,player_id BIGINT NOT NULL REFERENCES players(id),source_id BIGINT NOT NULL REFERENCES players(id),level INTEGER NOT NULL CHECK(level BETWEEN 1 AND 3),amount_micros NUMERIC(30,0) NOT NULL CHECK(amount_micros>0),created_at BIGINT NOT NULL);
 `;for(const sql of schema.split(';').filter(x=>x.trim()))await this.finance.pool.query(sql);}
 async accrue(c,sourceId,sourceReference,cashMicros,now){
  let current=sourceId;const seen=new Set([sourceId]);for(let level=1;level<=3;level++){const r=await c.query('SELECT referrer_id FROM players WHERE id=$1',[current]),parent=r.rows[0]?.referrer_id?.toString();if(!parent||seen.has(parent))break;seen.add(parent);current=parent;const amount=BigInt(cashMicros)*BigInt([5,3,2][level-1])/100n;if(!amount)continue;
   const added=await c.query('INSERT INTO referral_rewards(reference,player_id,source_id,level,amount_micros,created_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING reference',[sourceReference+':F'+level,parent,sourceId,level,String(amount),now]);if(!added.rows.length)continue;
   await c.query('INSERT INTO referral_accounts(player_id,pending_micros,total_micros) VALUES($1,$2,$2) ON CONFLICT(player_id) DO UPDATE SET pending_micros=referral_accounts.pending_micros+EXCLUDED.pending_micros,total_micros=referral_accounts.total_micros+EXCLUDED.total_micros',[parent,String(amount)]);
  }
 }
 async summary(id){const p=this.finance.pool,r=await p.query('SELECT * FROM referral_accounts WHERE player_id=$1',[id]),counts=await p.query('WITH RECURSIVE team AS (SELECT id,1 AS level FROM players WHERE referrer_id=$1 UNION ALL SELECT p.id,t.level+1 FROM players p JOIN team t ON p.referrer_id=t.id WHERE t.level<3) SELECT level,count(*) AS count FROM team GROUP BY level',[id]),earned=await p.query('SELECT level,sum(amount_micros) AS earned FROM referral_rewards WHERE player_id=$1 GROUP BY level',[id]);return {link:'https://t.me/AquaViewGameBot?startapp=ref_'+id,pendingMicros:String(r.rows[0]?.pending_micros||0),totalMicros:String(r.rows[0]?.total_micros||0),minimumCash:1000,levels:[1,2,3].map(level=>({level,percent:[5,3,2][level-1],count:Number(counts.rows.find(x=>x.level===level)?.count||0),earnedMicros:String(earned.rows.find(x=>x.level===level)?.earned||0)}))};}
 async collect(id,now=Date.now()){return this.finance.transaction(async c=>{await this.finance.account(c,id);const r=await c.query('SELECT * FROM referral_accounts WHERE player_id=$1 FOR UPDATE',[id]),a=r.rows[0];if(!a||BigInt(a.pending_micros)<1000000000n)throw Error('Necesitas al menos 1,000 CASH de referidos para recoger.');await c.query('UPDATE referral_accounts SET pending_micros=0 WHERE player_id=$1',[id]);await c.query('UPDATE finance_accounts SET cash_micros=cash_micros+$2 WHERE player_id=$1',[id,String(a.pending_micros)]);await this.finance.event(c,id,'referral-collect:'+randomUUID(),'referral_collect',0,String(a.pending_micros),0,now);return {message:'Recogiste '+(Number(a.pending_micros)/1e6).toLocaleString('es')+' CASH de referidos.'};});}
}
